version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    ports:
      - "4466:4466"
    restart: always
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: postgres
            host: ${DB_HOST}
            user: ${DB_USER}
            password: ${DB_PASSWORD}
            port: 5432
            migrations: true
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  phoenix:
    image: rctechclub/phoenix:dev
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PRISMA_HOST=${PRISMA_HOST}
      - PRISMA_SECRET=${PRISMA_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    depends_on:
      - prisma
      - postgres
  ladybird:
    image: rctechclub/ladybird:latest
    restart: always
    ports:
      - "3001:3001"
volumes:
  postgres:
