version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - rctech-dev:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  phoenix:
    image: rctechclub/phoenix:dev
    restart: always
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - NODEMAILER_PASSWORD=${NODEMAILER_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SLS_SECRET=${SLS_SECRET}
    depends_on:
      - postgres
  ladybird:
    image: rctechclub/ladybird:latest
    restart: always
    ports:
      - 3001:80
    depends_on:
      - phoenix

volumes:
  rctech-dev:
